// GENERATED by `supabase gen types typescript`. DO NOT EDIT BY HAND.
// Regenerate with `npm run gen:types` after any migration change.
// PostGIS geography/geometry columns surface as loose types — wrap with Zod at feature api/.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      achievements: {
        Row: {
          code: string
          created_at: string
          description: string | null
          icon: string | null
          id: string
          name: string
        }
        Insert: {
          code: string
          created_at?: string
          description?: string | null
          icon?: string | null
          id?: string
          name: string
        }
        Update: {
          code?: string
          created_at?: string
          description?: string | null
          icon?: string | null
          id?: string
          name?: string
        }
        Relationships: []
      }
      check_ins: {
        Row: {
          created_at: string
          driven_at: string
          id: string
          note: string | null
          road_id: string
          user_id: string
          vehicle_id: string | null
        }
        Insert: {
          created_at?: string
          driven_at?: string
          id?: string
          note?: string | null
          road_id: string
          user_id: string
          vehicle_id?: string | null
        }
        Update: {
          created_at?: string
          driven_at?: string
          id?: string
          note?: string | null
          road_id?: string
          user_id?: string
          vehicle_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "check_ins_road_id_fkey"
            columns: ["road_id"]
            isOneToOne: false
            referencedRelation: "roads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "check_ins_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "check_ins_vehicle_id_fkey"
            columns: ["vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles"
            referencedColumns: ["id"]
          },
        ]
      }
      comments: {
        Row: {
          body: string
          created_at: string
          id: string
          road_id: string
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          road_id: string
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          road_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "comments_road_id_fkey"
            columns: ["road_id"]
            isOneToOne: false
            referencedRelation: "roads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "comments_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      favorites: {
        Row: {
          created_at: string
          road_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          road_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          road_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "favorites_road_id_fkey"
            columns: ["road_id"]
            isOneToOne: false
            referencedRelation: "roads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "favorites_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          bio: string | null
          created_at: string
          display_name: string | null
          id: string
        }
        Insert: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          display_name?: string | null
          id: string
        }
        Update: {
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          display_name?: string | null
          id?: string
        }
        Relationships: []
      }
      road_photos: {
        Row: {
          caption: string | null
          created_at: string
          id: string
          road_id: string
          storage_path: string
          user_id: string | null
        }
        Insert: {
          caption?: string | null
          created_at?: string
          id?: string
          road_id: string
          storage_path: string
          user_id?: string | null
        }
        Update: {
          caption?: string | null
          created_at?: string
          id?: string
          road_id?: string
          storage_path?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "road_photos_road_id_fkey"
            columns: ["road_id"]
            isOneToOne: false
            referencedRelation: "roads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "road_photos_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      road_reports: {
        Row: {
          body: string
          created_at: string
          id: string
          road_id: string
          type: Database["public"]["Enums"]["road_report_type"]
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          road_id: string
          type: Database["public"]["Enums"]["road_report_type"]
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          road_id?: string
          type?: Database["public"]["Enums"]["road_report_type"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "road_reports_road_id_fkey"
            columns: ["road_id"]
            isOneToOne: false
            referencedRelation: "roads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "road_reports_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      road_segments: {
        Row: {
          avg_radius_m: number | null
          difficulty: Database["public"]["Enums"]["difficulty"]
          difficulty_score: number | null
          geom: unknown
          gradient_pct: number | null
          heading_change_deg: number | null
          id: string
          length_m: number | null
          min_radius_m: number | null
          order_index: number
          road_id: string
          surface_quality: Database["public"]["Enums"]["surface_quality"] | null
        }
        Insert: {
          avg_radius_m?: number | null
          difficulty: Database["public"]["Enums"]["difficulty"]
          difficulty_score?: number | null
          geom: unknown
          gradient_pct?: number | null
          heading_change_deg?: number | null
          id?: string
          length_m?: number | null
          min_radius_m?: number | null
          order_index: number
          road_id: string
          surface_quality?:
            | Database["public"]["Enums"]["surface_quality"]
            | null
        }
        Update: {
          avg_radius_m?: number | null
          difficulty?: Database["public"]["Enums"]["difficulty"]
          difficulty_score?: number | null
          geom?: unknown
          gradient_pct?: number | null
          heading_change_deg?: number | null
          id?: string
          length_m?: number | null
          min_radius_m?: number | null
          order_index?: number
          road_id?: string
          surface_quality?:
            | Database["public"]["Enums"]["surface_quality"]
            | null
        }
        Relationships: [
          {
            foreignKeyName: "road_segments_road_id_fkey"
            columns: ["road_id"]
            isOneToOne: false
            referencedRelation: "roads"
            referencedColumns: ["id"]
          },
        ]
      }
      roads: {
        Row: {
          bbox: unknown
          best_time_window: string | null
          centerline: unknown
          country: string | null
          cover_photo_url: string | null
          created_at: string
          curated: boolean
          description: string | null
          id: string
          length_m: number | null
          name: string
          region: string | null
          scenic_rating: number | null
        }
        Insert: {
          bbox?: unknown
          best_time_window?: string | null
          centerline: unknown
          country?: string | null
          cover_photo_url?: string | null
          created_at?: string
          curated?: boolean
          description?: string | null
          id?: string
          length_m?: number | null
          name: string
          region?: string | null
          scenic_rating?: number | null
        }
        Update: {
          bbox?: unknown
          best_time_window?: string | null
          centerline?: unknown
          country?: string | null
          cover_photo_url?: string | null
          created_at?: string
          curated?: boolean
          description?: string | null
          id?: string
          length_m?: number | null
          name?: string
          region?: string | null
          scenic_rating?: number | null
        }
        Relationships: []
      }
      user_achievements: {
        Row: {
          achievement_id: string
          earned_at: string
          user_id: string
        }
        Insert: {
          achievement_id: string
          earned_at?: string
          user_id: string
        }
        Update: {
          achievement_id?: string
          earned_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_achievements_achievement_id_fkey"
            columns: ["achievement_id"]
            isOneToOne: false
            referencedRelation: "achievements"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_achievements_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      vehicle_setups: {
        Row: {
          id: string
          notes: string | null
          suspension: string | null
          tires: string | null
          updated_at: string
          vehicle_id: string
        }
        Insert: {
          id?: string
          notes?: string | null
          suspension?: string | null
          tires?: string | null
          updated_at?: string
          vehicle_id: string
        }
        Update: {
          id?: string
          notes?: string | null
          suspension?: string | null
          tires?: string | null
          updated_at?: string
          vehicle_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "vehicle_setups_vehicle_id_fkey"
            columns: ["vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles"
            referencedColumns: ["id"]
          },
        ]
      }
      vehicles: {
        Row: {
          color: string | null
          id: string
          make: string | null
          model: string | null
          notes: string | null
          user_id: string
          year: number | null
        }
        Insert: {
          color?: string | null
          id?: string
          make?: string | null
          model?: string | null
          notes?: string | null
          user_id: string
          year?: number | null
        }
        Update: {
          color?: string | null
          id?: string
          make?: string | null
          model?: string | null
          notes?: string | null
          user_id?: string
          year?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "vehicles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      difficulty: "easy" | "medium" | "technical" | "hairpin"
      road_report_type: "surface" | "hazard" | "closure" | "scenic" | "note"
      surface_quality: "excellent" | "good" | "fair" | "poor" | "unpaved"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      difficulty: ["easy", "medium", "technical", "hairpin"],
      road_report_type: ["surface", "hazard", "closure", "scenic", "note"],
      surface_quality: ["excellent", "good", "fair", "poor", "unpaved"],
    },
  },
} as const

